Sqlfluff - Refactor and update the extension
sqlfluff/vscode-sqlfluff pull request #50
Opened 2022-07-11 20:27 UTC by RobertOstermann

This pulls in the changes from my `sqlfluff extended` extension.

2022-07-12 16:54 UTC, alanmcruickshank commented
@dorzey - would you be able to review this one? I'm afraid it's far beyond my JS-Fu.

2022-07-12 16:55 UTC, alanmcruickshank commented
@RobertOstermann - if he's not able to review then I'll do my best in a few days time. Thanks for taking the time to put this together 🙏

2022-07-12 17:11 UTC, tunetheweb requested changes
Don't know VS code extensions, my JS knowledge is weak, and my TS knowledge is non-existent :-)

But did spot a couple of minor things.

2022-07-12 17:11 UTC, tunetheweb commented on test/.sqlfluff
> +extended_capitalisation_policy = lower
Nit, missing end of file newline

```suggestion
extended_capitalisation_policy = lower

```

2022-07-13 21:44 UTC, RobertOstermann commented
@tunetheweb I have made the changes you requested. I also noticed a few more problems when looking through my code and testing the extension. I have fixed those issues in recent commits.

2022-07-29 14:47 UTC, merged